; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.36"

; Modules
projects[admin_menu][version] = "3.0-rc5"

projects[apachesolr][version] = "1.7"

projects[ctools][version] = "1.7"

projects[facetapi][version] = "1.5"

projects[devel][version] = "1.5"

projects[entity][version] = "1.6"

projects[facetapi_pretty_paths][version] = "1.4"

projects[features][version] = "2.5"

projects[search_api][version] = "1.14"

projects[search_api_solr][version] = "1.6"

projects[views][version] = "3.11"

