<?php
/**
 * @file
 * This module contains mentorship Solr task.
 */

/**
 * Implements hook_block().
 */
function custom_solr_block_info() {
  // Top user menu.
  $blocks['custom_query_search'] = array(
    'info' => t('Printing the custom query search'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function custom_solr_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'custom_query_search':
      $block['subject'] = t('Custom query Solr');
      $block['content'] = some_custom_solr_query();
      break;

  }

  return $block;
}

/**
 * Custom function for printing custom Solr query.
 */
function some_custom_solr_query() {
  global $language;

  // Loading server and index.
  $server = search_api_server_load('solr');
  $index = search_api_index_load('solr_index');

  // Search by keywords.
  $query = new SearchApiQuery($index);
  $query->keys('Abdo')
    ->fields(array('title', 'body:value'))
    ->condition('language', $language->language, '=')
    ->range(0, 10);

  // Create filters.
  $filter = $query->createFilter('AND');
  $filter->condition('type', 'article', '=');

  $solr = new SearchApiSolrService($server);
  $result = $solr->search($query);

  // Theme item list for Result in title.
  $results['items'] = array();
  $results['title'] = 'Results from custom query:';
  $results['type'] = 'ul';
  $results['attributes']['class'] = '';
  foreach ($result['results'] as $id) {
    // Setting items with link to node page.
    $results['items'][] = l(
      $result['results'][$id['id']]['fields']['title'][0],
      'node/' . $result['results'][$id['id']]['fields']['nid']
    );
  }
  $results_title = theme_item_list($results);

  return $results_title;
}

/**
 * Implements hook_form_alter().
 */
function custom_solr_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'webform_client_form_66':
      // Setting captcha at the last page of webform.
      $page_num = $form['details']['page_num']['#value'];
      $page_count = $form['details']['page_count']['#value'];
      if ($page_num != $page_count) {
        unset($form['captcha']);
      }
      $form['#validate'][] = 'custom_solr_form_validate';

      break;
  }

  return $form;
}

/**
 * Custom validate function.
 *
 * @param array $form
 *   Form data.
 * @param array $form_state
 *   Form state data.
 */
function custom_solr_form_validate($form, &$form_state) {
  if (isset($form)) {
    if ($form['form_id']['#value'] == 'webform_client_form_66') {
      switch ($form['details']['page_num']['#value']) {
        case 1:
          $minimum_length = 2;
          if (strlen($form_state['values']['submitted']['first_name']) < $minimum_length) {
            form_set_error('submitted][first_name', t('First name is too short need at least 2 characters.'));
          }
          if (strlen($form_state['values']['submitted']['last_name']) < $minimum_length) {
            form_set_error('submitted][last_name', t('Last name is too short need at least 2 characters.'));
          }
          if (strpos($form_state['values']['submitted']['e_mail_adress'], 'mail.ru') ||
            strpos($form_state['values']['submitted']['e_mail_adress'], 'yandex.ru')
          ) {
            form_set_error('submitted][e_mail_adress', t('Domain zones from mail.ru and yandex.ru are not allowed'));
          }
          break;

        case 2:
          if (preg_match('#[0-9]#', $form_state['values']['submitted']['home_adress']['form_city'])) {
            form_set_error('form_city', t("City can't contain numbers"));
            break;
          }
      }
    }
  }
}

/**
 * Implements hook_views_pre_render().
 */
function custom_solr_views_pre_render(&$view) {
  if ($view->name == 'node_reference_webform') {
    foreach ($view->_webform_submissions as $key => $array) {
      foreach ($array as $webfrom_key => $values) {
        $nid = $view->_webform_submissions[$key][$webfrom_key]->data[3][0];
      }
      $node = node_load($nid);
      $wrapper = entity_metadata_wrapper('node', $node);
      $field_image = $wrapper->field_image->value();
      if ($field_image) {
        $uri = $field_image['uri'];
        $filename = $field_image['filename'];
        $url = file_create_url($uri);
        $output = theme('image', array('path' => $url));
        $view->header['area_text_custom']->options['content'] = $output;
      }
    }
  }
}
